export const dom = {
    themeSelect: document.getElementById("themeSelect"),
    tabs: document.querySelectorAll('[role="tab"]'),
    tabList: document.querySelector('[role="tablist"]'),
    userInput: document.getElementById("userInput"),
    repoInput: document.getElementById("repoInput"),
    tokenInput: document.getElementById("tokenInput"),
    saveSettings: document.getElementById("saveSettings"),
    resetGitHubSettings: document.getElementById("resetGitHubSettings"),
    resetGitHubSettingsDialog: document.getElementById("resetGitHubSettingsDialog"),
    resetGitHubSettingsYes: document.getElementById("resetGitHubSettingsYes"),
    resetGitHubSettingsNo: document.getElementById("resetGitHubSettingsNo"),
    logSettings: document.getElementById("logSettings"),
    noteInput: document.getElementById("noteInput"),
    faviconImg: document.getElementById("faviconImg"),
    faviconUrl: document.getElementById("faviconUrl"),
    faviconNotFound: document.getElementById("faviconNotFound"),
    titleInput: document.getElementById("titleInput"),
    descInput: document.getElementById("descInput"),
    urlInput: document.getElementById("urlInput"),
    screenshotImg: document.getElementById("screenshotImg"),
    screenshotCode: document.getElementById("screenshotCode"),
    log: document.getElementById("log"),
    saveButton: document.getElementById("saveButton")
};